# Generated by Django 6.0.4 on 2026-04-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_uc_semestre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="licenciatura",
            name="uc",
        ),
        migrations.AddField(
            model_name="semestre",
            name="ano",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Ano",
        ),
    ]
