# Generated by Django 6.0.4 on 2026-04-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_remove_licenciatura_uc_semestre_ano_delete_ano"),
    ]

    operations = [
        migrations.AddField(
            model_name="uc",
            name="ano",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uc",
            name="semestre",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Semestre",
        ),
    ]
