# Generated by Django 6.0.4 on 2026-04-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_uc_ano_uc_semestre_delete_semestre"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenciatura",
            name="uc",
            field=models.ManyToManyField(
                blank=True, related_name="licenciaturas", to="portfolio.uc"
            ),
        ),
    ]
