# Generated by Django 6.0.4 on 2026-04-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_licenciatura_uc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("mail", models.CharField(max_length=100)),
                ("site", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="uc",
            name="docente",
            field=models.ManyToManyField(related_name="ucs", to="portfolio.docente"),
        ),
    ]
