# Generated by Django 6.0.4 on 2026-04-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_docente_uc_docente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Projetos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=500)),
                ("repositorio", models.CharField(max_length=100)),
                ("conceitos", models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name="uc",
            name="imagem",
            field=models.ImageField(blank=True, upload_to="fotos_uc/"),
        ),
    ]
