# Generated by Django 6.0.4 on 2026-04-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_competencias_projetos_uc_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("site_oficial", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=500)),
                ("logo", models.ImageField(blank=True, upload_to="fotos_tecnologia/")),
            ],
        ),
        migrations.RenameModel(
            old_name="Projetos",
            new_name="Projeto",
        ),
        migrations.DeleteModel(
            name="Competencias",
        ),
    ]
