# Generated by Django 6.0.4 on 2026-04-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_tecnologia_rename_projetos_projeto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tecnologia",
            name="classificacao",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
