# Generated by Django 6.0.4 on 2026-04-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_tecnologia_classificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="tecnologia",
            field=models.ManyToManyField(
                related_name="projetos", to="portfolio.tecnologia"
            ),
        ),
    ]
