# Generated by Django 6.0.4 on 2026-04-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_projeto_tecnologia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("s", "Soft Skill"), ("h", "Hard Skill")], max_length=1
                    ),
                ),
            ],
        ),
    ]
