# Generated by Django 6.0.4 on 2026-04-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_competencia_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="competencia",
            field=models.ManyToManyField(
                related_name="projetos", to="portfolio.competencia"
            ),
        ),
    ]
