# Generated by Django 6.0.4 on 2026-04-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_projeto_competencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competencia",
            name="tipo",
            field=models.CharField(max_length=100),
        ),
    ]
