# Generated by Django 6.0.4 on 2026-04-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_alter_competencia_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=100)),
                ("data", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="docente",
            name="mail",
            field=models.EmailField(max_length=254),
        ),
    ]
