# Generated by Django 6.0.4 on 2026-04-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_formacao_alter_docente_mail"),
    ]

    operations = [
        migrations.AddField(
            model_name="tecnologia",
            name="formacao",
            field=models.ManyToManyField(
                blank=True, related_name="tecnologias", to="portfolio.formacao"
            ),
        ),
    ]
