# Generated by Django 6.0.4 on 2026-04-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0016_tecnologia_formacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fotos", models.ImageField(blank=True, upload_to="fotos_makingof/")),
                ("descricao", models.CharField(max_length=500)),
                ("alteracao", models.CharField(blank=True, max_length=500)),
                ("justificacao", models.CharField(blank=True, max_length=500)),
                ("llm", models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
