# Generated by Django 6.0.4 on 2026-04-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_makingof"),
    ]

    operations = [
        migrations.AddField(
            model_name="uc",
            name="descricao",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
