# Generated by Django 6.0.4 on 2026-04-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0018_uc_descricao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tfc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("aluno", models.CharField(max_length=100)),
                ("orientador", models.CharField(max_length=100)),
                ("licenciatura", models.CharField(max_length=100)),
                ("pdf", models.URLField()),
                ("mail", models.EmailField(max_length=254)),
                ("resumo", models.TextField()),
                ("palavras_chave", models.CharField(max_length=100)),
                ("tecnologias", models.CharField(max_length=100)),
                ("rating", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="competencia",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="docente",
            name="site",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="site_oficial",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="uc",
            name="descricao",
            field=models.TextField(),
        ),
    ]
