# Generated by Django 6.0.4 on 2026-04-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0019_tfc_alter_competencia_descricao_alter_docente_site_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tfc",
            name="area",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
