# Generated by Django 6.0.4 on 2026-04-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0020_tfc_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="uc",
            name="avaliacao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="uc",
            name="ects",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uc",
            name="objetivo",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="uc",
            name="programa",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="uc",
            name="descricao",
            field=models.TextField(blank=True),
        ),
    ]
