# Generated by Django 6.0.4 on 2026-04-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0021_uc_avaliacao_uc_ects_uc_objetivo_uc_programa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uc",
            name="semestre",
            field=models.CharField(max_length=20),
        ),
    ]
