# Generated by Django 6.0.4 on 2026-04-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0022_alter_uc_semestre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uc",
            name="avaliacao",
        ),
    ]
