# Generated by Django 6.0.4 on 2026-04-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0023_remove_uc_avaliacao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="docente",
            old_name="mail",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="tfc",
            old_name="mail",
            new_name="email",
        ),
        migrations.RemoveField(
            model_name="docente",
            name="site",
        ),
        migrations.AddField(
            model_name="docente",
            name="card_code",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="docente",
            name="degree",
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="docente",
            name="employee_code",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="docente",
            name="regime",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
