# Generated by Django 6.0.4 on 2026-04-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0024_rename_mail_docente_email_rename_mail_tfc_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
