# Generated by Django 6.0.4 on 2026-04-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0026_alter_docente_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="email",
            field=models.EmailField(default="Não disponível", max_length=254),
        ),
    ]
