# Generated by Django 6.0.4 on 2026-04-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0027_alter_docente_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="card_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="docente",
            name="degree",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="docente",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="docente",
            name="employee_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="docente",
            name="regime",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
