# Generated by Django 6.0.4 on 2026-04-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0028_alter_docente_card_code_alter_docente_degree_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="card_code",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="docente",
            name="degree",
            field=models.CharField(default="Não disponível", max_length=100),
        ),
        migrations.AlterField(
            model_name="docente",
            name="email",
            field=models.EmailField(default="Não disponível", max_length=254),
        ),
        migrations.AlterField(
            model_name="docente",
            name="employee_code",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="docente",
            name="regime",
            field=models.CharField(max_length=100),
        ),
    ]
