# Generated by Django 6.0.4 on 2026-04-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0029_alter_docente_card_code_alter_docente_degree_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="email",
            field=models.EmailField(
                blank=True, default="Não disponível", max_length=254
            ),
        ),
    ]
