# Generated by Django 6.0.4 on 2026-04-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0032_alter_docente_degree_alter_docente_regime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="degree",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="docente",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
