# Generated by Django 6.0.4 on 2026-04-09 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0033_alter_docente_degree_alter_docente_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="uc",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ucs",
                to="portfolio.projeto",
            ),
            preserve_default=False,
        ),
    ]
