# Generated by Django 6.0.4 on 2026-04-09 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0034_uc_projeto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uc",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ucs",
                to="portfolio.projeto",
            ),
        ),
    ]
