# Generated by Django 6.0.4 on 2026-04-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0035_alter_uc_projeto"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenciatura",
            name="curso_codigo",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="curso_ects",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="objetivos",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="descricao",
            field=models.TextField(),
        ),
    ]
