# Generated by Django 6.0.4 on 2026-04-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0036_licenciatura_curso_codigo_licenciatura_curso_ects_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenciatura",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="objetivos",
            field=models.TextField(blank=True),
        ),
    ]
