# Generated by Django 6.0.4 on 2026-04-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0037_alter_licenciatura_descricao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenciatura",
            name="semestres",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
