# Generated by Django 6.0.4 on 2026-04-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0038_licenciatura_semestres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uc",
            name="docente",
            field=models.ManyToManyField(
                blank=True, related_name="ucs", to="portfolio.docente"
            ),
        ),
    ]
