# Generated by Django 6.0.4 on 2026-04-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0039_alter_uc_docente"),
    ]

    operations = [
        migrations.AddField(
            model_name="makingof",
            name="titulo",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projeto",
            name="repositorio",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
