# Generated by Django 6.0.4 on 2026-04-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0040_makingof_titulo_alter_projeto_repositorio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makingof",
            name="justificacao",
            field=models.TextField(blank=True),
        ),
    ]
