# Generated by Django 6.0.4 on 2026-04-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0041_alter_makingof_justificacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makingof",
            name="alteracao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="descricao",
            field=models.TextField(blank=True),
        ),
    ]
