# Generated by Django 6.0.4 on 2026-04-23 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0042_alter_makingof_alteracao_alter_makingof_descricao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uc",
            name="projeto",
        ),
        migrations.AddField(
            model_name="projeto",
            name="uc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="portfolio.uc",
            ),
        ),
    ]
