# Generated by Django 6.0.4 on 2026-05-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0043_remove_uc_projeto_projeto_uc"),
    ]

    operations = [
        migrations.AddField(
            model_name="tecnologia",
            name="portfolio",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
