# Generated by Django 6.0.5 on 2026-05-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0044_tecnologia_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="aluno",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="area",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="licenciatura",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="palavras_chave",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="tecnologias",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.TextField(),
        ),
    ]
