# Generated by Django 6.0.4 on 2026-05-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artigo",
            name="fotografia",
            field=models.ImageField(blank=True, null=True, upload_to="artigos/"),
        ),
    ]
