# Generated by Django 6.0.4 on 2026-05-15 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0002_alter_artigo_fotografia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="artigo",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_artigos", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
